name: trimix
description: Trimix Video Editor
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  ffmpeg_kit_flutter: ^6.0.1
  video_player: ^2.9.5
  file_picker: ^8.0.0
  path_provider: ^2.1.4

flutter:
  uses-material-design: true
