name: trimix
description: Trimix Video Editor
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  ffmpeg_kit_flutter: 6.0.3
  video_editor: 2.0.5
  video_player: 2.8.4
  file_picker: ^8.0.0
  path_provider: 2.1.3
  gallery_saver: 2.3.2
  permission_handler: 11.3.1

flutter:
  uses-material-design: true

dependency_overrides:
  video_editor: 2.0.5
  ffmpeg_kit_flutter: 6.0.3
